看了一点，感觉就像是   ---》   do while如果错误就break（感觉很像，而且加强了）

异常是跨函数的，（如果本函数中有throw和try，先会在本函数中看）如果调用的没有try，就会去更上一级

但是如果抛出异常，但是没人处理，就会坏

异常也可以继续往外扔，这时候直接throw就可以了

总结：
1.发生异常之后，是跨函数
2.接受异常以后，可以不处理，再抛出异常（throw）
3.catch异常时  是按照类型接异常（严格按照类型匹配）




异常的思想：
异常的引发和异常的处理不必在同一个函数中
使得底层的函数可以着重解决具体问题
而不必过多的考虑异常的处理，上层调用者在适当的位置处理
（分层更好一些）



栈解锁：
异常被抛出后，从进入try块起，到异常抛出前
这期间栈上的构造的所有对象都会被自动析构
析构顺序和构造顺序相反

这一现象被称作栈解旋